### ISSUE TITLE
Create a Gofile.io module.

### ISSUE THREAD

**Issue by cmsteffen-code** [cmsteffen-code/FileRoulette#10]
We could really use a module for gofile.io. This would go in `fileroulette/modules/gofile.py`. The constraints are as follows:

    self.base_url = "https://gofile.io/?c={}"
    self.allowed_chars = "a1"
    self.key_length = 6

With a key length of 6 and 36 possible characters in the mix, this has a total of `2,176,782,336` possible combinations.

**Comment by headrx** [comment]
Added gofileio.py module.
